### ISSUE TITLE
Dynamic libraries in custom locations not found when running the generated binary.

### ISSUE THREAD

**Issue by salva** [mattn/p5-Devel-CheckLib#19]
When some dynamic library is in a custom directory (not in the default library search path as declared in env `LD_LIBRARY_PATH` or in `ld.so.conf),  passed in`incpath`and`libpath`, the library is able to compile and link the binary. But then, in the case of using some custom function that really needs the library loaded at runtime when the generated program is executed, it fails because the dynamic library can not be found.

For a real example of this happening see the following script: [unrpath.t](https://github.com/salva/p5-Devel-CheckLib/blob/broken/broken/unrpath.t). In my Linux box I have libssh2 compiled as a dynamic library at `/usr/local/libssh2` and when the test program generated by Devel::CheckLib is run, it fails to find it:

```
$ perl -Ilib broken/unrpath.t
# Compiler seems to be /usr/bin/x86_64-linux-gnu-gcc
# /usr/bin/x86_64-linux-gnu-gcc -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fstack-protector-strong -L/usr/local/lib assertlibR8LAj8Q5.c -I/usr/local/libssh2/include -o assertlibvAhBNj9x
# /usr/bin/x86_64-linux-gnu-gcc -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fstack-protector-strong -L/usr/local/lib assertlibLQ9tqTOC.c -o assertlibGdSMn__w -I/usr/local/libssh2/include -L/usr/local/libssh2/lib -lssh2
/home/salva/g/perl/p5-Devel-CheckLib/assertlibGdSMn__w: error while loading shared libraries: libssh2.so.1: cannot open shared object file: No such file or directory
wrong result: 'ssh2'
```

As a workaround, using the `ldflags` feature I have just submitted in a pull request, I can tell Devel::CheckLib to link with `-rpath=$libpath`:

```
$ perl -Ilib broken/unrpath.t 1
# Compiler seems to be /usr/bin/x86_64-linux-gnu-gcc
# /usr/bin/x86_64-linux-gnu-gcc -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fstack-protector-strong -L/usr/local/lib -Wl,-rpath=/usr/local/libssh2/lib assertlibK3ufAM2E.c -I/usr/local/libssh2/include -o assertlibLKT2h60Q
# /usr/bin/x86_64-linux-gnu-gcc -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fstack-protector-strong -L/usr/local/lib -Wl,-rpath=/usr/local/libssh2/lib assertlibkU0crzZC.c -o assertlibqBzLfxar -I/usr/local/libssh2/include -L/usr/local/libssh2/lib -lssh2
```

But this is just a workaround. I don't really know how this issue could be fixed in a generic way. Also, it should be noted that, any custom flags required to compile the program should also be passed back to the program calling the library because otherwise the same logic should also be replicated there.

**Comment by toddr** [comment]
Also seen in DBD::mysql when they added Devel::CheckLib - https://github.com/perl5-dbi/DBD-mysql/issues/109

**Comment by mattn** [comment]
What way do you want to fix this? Environment variable for the path to the location?

**Comment by toddr** [comment]
ExtUtils::MakeMaker seems to be able to figure out how to set LD_RUN_PATH as part of GCC. I'd hope we could steal that logic.
