### ISSUE TITLE
Update bug reporting instructions

### ISSUE THREAD

**Issue by ryandesign** [mattn/p5-Devel-CheckLib#33]
bin/use-devel-checklib and lib/Devel/CheckLib.pm both say

> ```
> Bug reports should be made using L<http://rt.cpan.org/> or by email.
> ```

but [rt.cpan.org will shut down March 1, 2021](https://log.perl.org/2020/12/rtcpanorg-sunset.html). You should update those instructions. Presumably you would like users to file issues here on GitHub instead.

**Comment by mohawk2** [comment]
RT was not shut down, so that implies this can now be closed?

**Comment by ryandesign** [comment]
Interesting. Thanks for letting me know.
